### ISSUE TITLE
Unnecessary trigger 

### ISSUE THREAD

**Issue by a-bardai** [pivotal-cf/pivnet-resource#124] opened 2019-12-02 16:56 UTC
Hi All,
We have a pipeline that is supposed to trigger based on pivnet product versions. But lately we are seeing strange behavior with it. Below is part of the pipeline:
```
resource_types:
  - name: pivnet
    type: docker-image
    source:
      repository: pivotalcf/pivnet-resource
      tag: latest-final

resources:
  - name: product
    type: pivnet
    source:
      api_token: ((pivnet_token))
      product_slug: ((product_slug))
      product_version: ((product_version))

jobs:
  - name: acquire-lock
    serial: true
    plan: 
      - get: product
        params:
          globs: 
          - ((product_glob))
        trigger: true
      - put: locks
        params: 
          claim: upload
 - name: upload-and-stage-tile
    serial: true
    plan:
      - in_parallel:
          - get: locks
            passed: 
              - acquire-lock
          - get: product
            params: 
              globs:
                - ((product_glob))
            passed: 
              - acquire-lock
            trigger: true
```
The 'acquire-lock' was triggered even though there was not a new version of the product. However, the 'upload-and-stage-tile' did not, which has the same criteria for trigger as 'acquire-lock'.

Any ideas why this would be?

**Comment by rszumlakowski** [comment] 2019-12-03 20:48
Hiya.  It's not clear to me why the `upload-and-stage-tile` job is not triggering, but I have a couple suggestions that could help you troubleshoot:

1. The `product_version` parameter on the Pivnet resource must be a properly formed regular expression.  Many people enter a glob there and find that their pipelines get triggered for unexpected releases.  We see this occurrence frequently.  The [Some Common Gotchas](https://github.com/pivotal-cf/pivnet-resource#some-common-gotchas) part of the documentation might help make this more clear.

2. Typically we would write the `upload-and-stage-file` job above to be a task that runs in the same job as `acquire-lock`.  If you combine these two jobs into one (say, called simply `upload-and-stage-file`), then you can `get` the same resources and you won't need to dd the `passed` or `trigger` attributes to them.  We use this pattern in our own pipelines on Concourse.

I hope that helps.

**Comment by a-bardai** [comment] 2019-12-04 15:10
Here is how the variables are currently defined:
product_slug: p-healthwatch
product_version:  ^1\.7\..*$
product_glob: "*.pivotal"

I'll change the version to be ^1\.7\.\d+$ per your suggestion. I'll also combine the lock step with the next step to be one step.

Still don't understand why it would trigger without any visible updates from pivnet.

Thanks for your suggestions.

**Comment by a-bardai** [comment] 2019-12-04 15:11
correction: product_slug is currently ^1.7..*$ (not sure why asterisk fell off the original post)

**Comment by rszumlakowski** [comment] 2019-12-05 14:55
If you are still seeing unnecessary triggers then could you please attach a screenshot of the resource from your Concourse pipeline (i.e.: not the job that uses the resource, but click on the resource itself and take a screenshot of all the past versions that the Pivnet resource has returned).  I'd like to see the list of versions it has triggered on, please.

**Comment by miguelverissimo** [comment] 2019-12-09 19:25
@a-bardai the screenshot would be very helpful, but I'm going out on a limb and speculate that any 1.7.x release will trigger any 1.7.x release, i.e. a new release on 1.7.2 will trigger 1.7.0, 1.7.1, etc.

The screenshot might help us to confirm this

**Comment by a-bardai** [comment] 2019-12-09 22:24
[cid:image001.png@01D5AEB5.0766F840]


[cid:image002.png@01D5AEB5.70FD4DE0]
These 2 runs have identical products. Run 10 should never have been triggered

**Comment by a-bardai** [comment] 2019-12-09 22:25
Sorry, not sure if the image came through. I replied to the auto generate email. Please let me know if you can see the image.

**Comment by a-bardai** [comment] 2019-12-09 22:28
![run9](https://user-images.githubusercontent.com/47335502/70478519-36d5d500-1aa9-11ea-8030-01d1cbf3273e.PNG)
![run10](https://user-images.githubusercontent.com/47335502/70478529-3ccbb600-1aa9-11ea-83b3-140be3bec633.PNG)

**Comment by a-bardai** [comment] 2019-12-10 13:40
Just to clarify, these screen shots are from before I created the issue. I haven't seen this occur since I created the issue. This happened 4 or 5 times before I created the issue.

**Comment by a-bardai** [comment] 2019-12-10 13:42
there is only one entry in the product check!

![product](https://user-images.githubusercontent.com/47335502/70534365-eb630b80-1b28-11ea-8d8d-c53bc287d7aa.PNG)

**Comment by rszumlakowski** [comment] 2020-01-09 20:44
I'm going to close this issue since it is no longer being reported as reproducible.

**Closed by rszumlakowski** 2020-01-09 20:44 UTC
