### ISSUE TITLE
WHOA - OUT OF MEMORY

### ISSUE THREAD

**Issue by zachgersh** [pivotal-cf/pivnet-resource#46] opened 2016-11-08 23:30 UTC
soooooooo, ran out of memory today - trying to upload a release is not happy (this was after one initial failed upload).

fully stack trace

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6b1793, 0x16)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc620500000, 0x200000000, 0x0, 0x7fd618)
	/usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0x7e4460, 0x200000000, 0x40df00)
	/usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0x7e4460, 0x100000, 0x0)
	/usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0x7e4460, 0x100000, 0x4301bf)
	/usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0x7e4460, 0x100000, 0x100000000, 0x2)
	/usr/local/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0xc42002ded0)
	/usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0x7e4460, 0x100000, 0x10100000000, 0xc4200d4060)
	/usr/local/go/src/runtime/mheap.go:580 +0x73
runtime.largeAlloc(0x1fffffe00, 0xc4200d4001, 0xc4201616e8)
	/usr/local/go/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xc420015500)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc4201615f0 sp=0xc4201615e8
runtime.mallocgc(0x1fffffe00, 0x64dac0, 0xc420161601, 0x44fed0)
	/usr/local/go/src/runtime/malloc.go:670 +0x903 fp=0xc420161690 sp=0xc4201615f0
runtime.makeslice(0x64dac0, 0x1fffffe00, 0x1fffffe00, 0x0, 0x0, 0xc4202df8d0)
	/usr/local/go/src/runtime/slice.go:57 +0x7b fp=0xc4201616e8 sp=0xc420161690
bytes.makeSlice(0x1fffffe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:198 +0x77 fp=0xc420161728 sp=0xc4201616e8
bytes.(*Buffer).ReadFrom(0xc4201617c8, 0x7c0f40, 0xc4202df8c0, 0xc4204afa00, 0x0, 0x200)
	/usr/local/go/src/bytes/buffer.go:170 +0x2a9 fp=0xc420161798 sp=0xc420161728
io/ioutil.readAll(0x7c0f40, 0xc4202df8c0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x147 fp=0xc420161848 sp=0xc420161798
io/ioutil.ReadAll(0x7c0f40, 0xc4202df8c0, 0xc4202df8c0, 0x7c0f40, 0xc4202df8c0, 0x1, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:42 +0x3e fp=0xc420161898 sp=0xc420161848
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet.Client.MakeRequest(0xc4200134d0, 0x21, 0xc4200ac8e0, 0x14, 0xc42006c380, 0x7b, 0x7c2d80, 0xc4200ac980, 0x0, 0xc42000cdc0, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/pivnet.go:205 +0x781 fp=0xc420161b60 sp=0xc420161898
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet.ProductFilesService.DownloadForRelease(0xc4200134d0, 0x21, 0xc4200ac8e0, 0x14, 0xc42006c380, 0x7b, 0x7c2d80, 0xc4200ac980, 0x0, 0xc42000cdc0, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/product_files.go:445 +0x33b fp=0xc420161ee0 sp=0xc420161b60
github.com/pivotal-cf/pivnet-resource/gp.Client.DownloadProductFile(0xc4200134d0, 0x21, 0xc4200ac8e0, 0x14, 0xc42006c380, 0x7b, 0x7c2d80, 0xc4200ac980, 0x0, 0xc42000cdc0, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/gp/gp.go:116 +0xbf fp=0xc420161fc8 sp=0xc420161ee0
github.com/pivotal-cf/pivnet-resource/gp.(*Client).DownloadProductFile(0xc42000d2c0, 0x7c1280, 0xc4200e6140, 0xc420011420, 0xf, 0xb10, 0x2371, 0x47d085, 0xc42000e8c0)
	<autogenerated>:19 +0xe9 fp=0xc4201620b0 sp=0xc420161fc8
github.com/pivotal-cf/pivnet-resource/downloader.Downloader.downloadProductFileWithRetries(0x7c09c0, 0xc42000d2c0, 0x7fff284d9ee1, 0xe, 0x7c2d80, 0xc4200ac980, 0x7c1280, 0xc4200e6140, 0xc420011420, 0xf, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/downloader/downloader.go:94 +0xbc fp=0xc420162140 sp=0xc4201620b0
github.com/pivotal-cf/pivnet-resource/downloader.Downloader.Download(0x7c09c0, 0xc42000d2c0, 0x7fff284d9ee1, 0xe, 0x7c2d80, 0xc4200ac980, 0xc4204dac00, 0x2, 0x4, 0xc420011420, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/downloader/downloader.go:70 +0x54f fp=0xc4201624c8 sp=0xc420162140
github.com/pivotal-cf/pivnet-resource/downloader.(*Downloader).Download(0xc420013500, 0xc4204dac00, 0x2, 0x4, 0xc420011420, 0xf, 0xb10, 0x486954, 0xc420020018, 0xc4201fe4e0, ...)
	<autogenerated>:2 +0xcc fp=0xc420162560 sp=0xc4201624c8
github.com/pivotal-cf/pivnet-resource/in.InCommand.downloadFiles(0x7c2d80, 0xc4200ac980, 0x0, 0x0, 0x7c5fc0, 0xc42000d2c0, 0x7c0980, 0xc420011510, 0x7c0940, 0xc420013500, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/in/in_command.go:301 +0x18d fp=0xc420162898 sp=0xc420162560
github.com/pivotal-cf/pivnet-resource/in.(*InCommand).Run(0xc420163c78, 0xc4200ac8e0, 0x14, 0xc420011420, 0xf, 0xc4200ac8c0, 0x14, 0xc420011430, 0x8, 0xc420013320, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/in/in_command.go:167 +0xc5a fp=0xc420163938 sp=0xc420162898
main.main()
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/cmd/in/main.go:98 +0xacc fp=0xc420163f28 sp=0xc420163938
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420163f80 sp=0xc420163f28
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420163f88 sp=0xc420163f80

goroutine 159 [select, 9 minutes]:
net/http.(*persistConn).writeLoop(0xc42051d900)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e

goroutine 158 [select, 9 minutes]:
net/http.(*persistConn).readLoop(0xc42051d900)
	/usr/local/go/src/net/http/transport.go:1541 +0x9c9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9
```

**Comment by robdimsdale** [comment] 2016-11-09 15:46
Interesting. You said this happened during a `put`, but I see **DownloadForRelease** in the stack trace:

```
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet.ProductFilesService.DownloadForRelease(...)
```

I haven't seen this out of memory issue before, and I can't reproduce it locally. However, looking at the code in github.com/pivotal-cf/go-pivnet, it appears that we are reading in the entire response body into memory for all requests (see [this line](https://github.com/pivotal-cf/go-pivnet/blob/master/pivnet.go#L205)) which is problematic when downloading large files.

I created a bug in the go-pivnet library - https://github.com/pivotal-cf/go-pivnet/issues/4 - which we can use to track this issue, so I'll close this now.

**Closed by robdimsdale** 2016-11-09 15:46 UTC
Labels: in progress
