### ISSUE TITLE
Using the resource through fly exec result in an error

### ISSUE THREAD

**Issue by carlo-colombo** [pivotal-cf/pivnet-resource#80] opened 2017-11-08 13:40 UTC
Trying to execute a task with fly exec that has as input pivnet resource and it fails with some variation of this error

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10240    0 10240    0     0  10240      0 --:--:-- --:--:-- --:--:-- 42845
183.54 MB / 183.54 MB [=================================] 100.00 % 91.21 MB/s 2star: /tmp/build/put/product: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    31    0     0    0    31      0     31 --:--:-- --:--:-- --:--:--    35
errored
```

```
11:58 $ fly -t kubo execute -c /tmp/extrac-releases.yml --inputs-from=[...]/build-product --output extracted-releases=/tmp/releases
executing build 25011 at https://ci.kubo.sh/teams/main/pipe[.....]bs//builds/17
base resource type not found
183.54 MB / 183.54 MB [=================================] 100.00 % 21.11 MB/s 8star: /tmp/build/put/extracted-releases: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    31    0     0    0    31      0     31 --:--:-- --:--:-- --:--:--    35
errored
```

Notes:

* `product` is the name of the output folder
* trying to search `/tmp/build/put` or variations in the source code does not seems to find anything relevant
* sometime instead of `2star`  in the error message `8star` was shown
* The resource in the pipeline on concourse behave correctly and we are able to use other resource in the same task without issue.

**Comment by ddadlani** [comment] 2018-05-14 20:26
Hello @carlo-colombo, we are not able to reproduce this error. Is this still a problem? Could you give us more information on how we can reproduce it locally?

**Comment by pnikonowicz** [comment] 2018-11-13 22:46
closing issue. 
if this issue persists please reopen.

**Closed by pnikonowicz** 2018-11-13 22:46 UTC
Labels: unscheduled
