### ISSUE TITLE
dependency_specifiers does not allow a specific verision to be specified

### ISSUE THREAD

**Issue by robertjsullivan** [pivotal-cf/pivnet-resource#63] opened 2017-02-01 23:19 UTC
I'm not sure if we're doing this wrong, or if this is potentially the new way of the world but there doesn't seem to be a way to say a product depends on a specific version of ERT.  Dependency specifiers require a major.minor.* pattern.  When depending on something like ERT with 1.9.* it uploads with 1.9.* in the dependencies section on PivNet instead of 1.9.0,1.9.1, 1.9.2, etc.  The old version using "dependencies" allowed you to specify the individual version.  I couldn't find any guidance on this in the docs.

This can be an issue if a product is incompatible with a specific version of a product dependency (for example: works with ERT 1.8.3 but not earlier versions of that 1.8 ERT)

**Comment by robdimsdale** [comment] 2017-02-02 06:05
@robertjsullivan you're correct, the `dependency_specifier` world is designed to specify an entire minor range, i.e. my product is dependent on other product versions `1.7.*`, or in the case of stemcells, a major range i.e. all stemcells in `3312.*`.

This is by design, as it is a bad experience for consumers of a product when it depends on a patch version of another, and so we are trying to move away from this behavior.

If you need to specify a specific patch dependency, you can still use `dependencies` directly instead of `dependency_specifiers`. It is deprecated but it likely won't be removed for some time while we still have older products that need this. I would strongly encourage all product authors to avoid specifying dependencies on patch versions of other products if at all possible, especially for newer products.

@crawsible any thoughts here?

**Comment by crawsible** [comment] 2017-02-02 15:19
@robertjsullivan Rob's correct on all counts; we do still support old-style dependencies although we discourage their use. There are some cases where they're unavoidable -- and indeed correct -- at the moment though, such as stemcell dependencies for tiles that don't yet float.

Dependency specifiers are a work in progress, so if you have a specific case that dependency specifiers cannot fit please let me know. Requiring an ERT >=1.8.3 is a use case that's on our radar, though we haven't yet heard of any new releases that would need to communicate that form of dependency. Are you in that situation at the moment?

**Comment by AmberAlston** [comment] 2017-02-02 18:13
@crawsible We have an example use case in pretty much every product we manage, and I do see this type of thing continuing, primarily driven by the on-going need for security backport patches, where we have to declare a dependency on a specific patch version for multiple minor versions of Ops Man and/or ERT (or sometimes product needed other tiles), typically in the >= format you mentioned. The first two examples below essentially follow your use case example, but we do that over multiple minors at once, not just one minor. The 3rd is the example of a quirky case but one we deal with. And the 4th an example of something PivNet does not handle well, and we've had to continue to handle with docs

- JMX Bridge product latest, had we proceeded with original security request to backport security work against Ops Man 1.8, 1.9, instead of waiting for 1.10/1.11, we would have had to declare >=x.x.X for JMX Bridge on 1.8.x 1.9.x Ops Mans; I expect that type of security work with patch backport dependencies to continue on all types of products 
- Log Search had a required firehose user change that was backported, so that older patch versions only worked with older ERT and then the newer LS patch versions only worked with certain ERT patch versions of multiple minors in >=x.x.X format
- PCF Metrics 1.0  (can't list "upgrades from" for v1.0.9 through v1.0.14) because of bugs that prevent successful upgrades from these versions 
- PCF Metrics 1.2: latest v1.2 declares special consideration on Ops Man for running (1.8.*) vs upgrading (1.7.8+) and ERT 1.8.9+ is minimum 1.8 patch version due to needed feature add in 1.8 required to run

**Comment by crawsible** [comment] 2017-02-06 18:02
@AmberAlston Thanks for those examples. We're going to start by addressing the "1.8.9+" specifier first (currently in the backlog); I'll circle up with you offline once it's done, so I can demo it for you and also better understand your other use-cases.

**Comment by dannysullivan** [comment] 2017-06-14 18:31
This is now implemented; closing this issue.

**Closed by dannysullivan** 2017-06-14 18:31 UTC
Labels: scheduled
